baseURL = 'http://www.marcuschiu.com/'
languageCode = 'en-US'

[menus]
  [[menus.main]]
    name = 'ğŸ  Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'ğŸ›  Tinkering'
    pageRef = '/tinkering'
    weight = 20

  [[menus.main]]
    name = 'ğŸ¨ Arting'
    pageRef = '/arting'
    weight = 30

  [[menus.main]]
    name = 'ğŸ’­ Rambling'
    pageRef = '/rambling'
    weight = 40

  [[menus.main]]
    name = 'ğŸŒ Traveling'
    pageRef = '/traveling'
    weight = 50

  [[menus.main]]
    name = 'ğŸ™‹ About'
    pageRef = '/about'
    weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
