baseURL = 'http://www.marcuschiu.com/'
languageCode = 'en-US'

[menus]
  [[menus.main]]
    name = 'ğŸ  Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'ğŸ›  Tinkerings'
    pageRef = '/tinkerings'
    weight = 20

  [[menus.main]]
    name = 'ğŸ¨ Artings'
    pageRef = '/artings'
    weight = 30

  [[menus.main]]
    name = 'ğŸ’­ Ramblings'
    pageRef = '/ramblings'
    weight = 40

  [[menus.main]]
    name = 'ğŸŒ Travelings'
    pageRef = '/travelings'
    weight = 50

  [[menus.main]]
    name = 'ğŸ™‹ About'
    pageRef = '/about'
    weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
